services:
    moonbird.talk.controller.acp:
        class: moonbird\talk\controller\acp_controller
        arguments:
            - '@config'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'

    moonbird.talk.service:
        class: moonbird\talk\service
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@moonbird.talk.curl_service'

    moonbird.talk.curl_service:
      class: moonbird\talk\curl_service

    moonbird.talk.listener:
        class: moonbird\talk\event\main_listener
        arguments:
            - '@moonbird.talk.service'
        tags:
            - { name: event.listener }

    moonbird.talk.notification.type.sample:
        class: moonbird\talk\notification\type\sample
        shared: false # service MUST not be shared for this to work!
        parent: notification.type.base
        calls:
            - [set_controller_helper, ['@controller.helper']]
        tags:
            - { name: notification.type }
